eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory
          uri: http://localhost:8081
          predicates:
            - Path=/api/inventory/**
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/api/order/**
        - id: product
          uri: http://localhost:8083
          predicates:
            - Path=/api/product/**